FROM debian:stretch
MAINTAINER Jeremy Letang <letang.jeremy@gmail.com>

RUN apt-get update && apt-get install -y libpq-dev libssl-dev

ADD ./migrations /_whlp/migrations
ADD whlp /whlp

ENV RUST_LOG=debug
ENV SSL_CERT_FILE=/usr/lib/ssl/certs/ca-certificates.crt
ENV SSL_CERT_DIR=/usr/lib/ssl/certs

RUN apt-cache policy libssl-dev

ENTRYPOINT ["/whlp"]
