FROM debian:latest
MAINTAINER Jeremy Letang <letang.jeremy@gmail.com>

RUN apt-get update && \
    apt-get install -y curl build-essential pkg-config

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly-2017-01-19
RUN apt-get install -y libpq-dev
RUN /root/.cargo/bin/cargo install diesel_cli --no-default-features --features postgres
ENV DATABASE_URL=postgres://root:root@pq_db:5432/unesco_whl

ADD entrypoint.sh /entrypoint.sh

CMD ["/entrypoint.sh"]